#! python3
# Password Detection Project // Chapter 7 - Automate the Boring Stuff
import re

def password_strength(password):
	password_status = True
	mo = re.compile(r'[a-z]') # Creates class for lowercase character
	mo2 = re.compile(r'[A-Z]') # Creates class for uppercase character
	mo3 = re.compile(r'[0-9]') # Creates class for number character
	if bool(mo.search(password)) == False: # Checks for lowercase character
		print('Password needs at least one lowercase character.')
		password_status = False
	if bool(mo2.search(password)) == False: # Checks for uppercase characer
		print('Password needs at least one uppercase character.')
		password_status = False
	if bool(mo3.search(password)) == False: # Checks for number
		print('Password needs at least one number.')
		password_status = False
	if len(password) <= 7: # Checks for length
		print('Password must be at least 8 characters long.')
		password_status = False

	if password_status == True: # Accepts secure password
		print('Password is secure.')


password = input('Please enter your password: ')

password_strength(password)
